apiVersion: v2
name: hcloud-pricing-exporter
description: A prometheus exporter for the current pricing and costs of your HCloud account
home: https://github.com/jangraefen/hcloud-pricing-exporter
maintainers:
  - name: Jan Graefen
sources:
  - https://github.com/jangraefen/hcloud-pricing-exporter
keywords:
  - hetzner
  - hcloud
  - prometheus
  - monitoring
  - prices
  - expenses

type: application

version: 0.9.0-r1
appVersion: 0.9.0

annotations:
  artifacthub.io/changes: |
    - Add support for Vault injected secrets
